version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Getting Started
  pre_build:
    commands:
      - echo DB USERNAME
      - echo $DB_USERNAME
      - echo Installing source NPM dependencies...
      - npm install
      - aws --version
      - echo node environment
      - echo $NODE_ENV
  build:
    commands:
      - echo Build started on `date`
      - echo first test codes
      - CI=true npm test
      - echo Compiling the codes
      - npm run build
      - echo Build finished, now moving to S3
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'buildspec/*'
  name: artifactbash